/**
 * RBAC example API
 * RBAC NestJS API with openapi integration for API client generation.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LikeDTO } from './likeDTO';

export interface PostDTO { 
    /**
     * Post content.
     */
    content: string;
    /**
     * Post ID
     */
    id: number;
    /**
     * Creation Date
     */
    creation_date: Date;
    /**
     * Post likes
     */
    likes: LikeDTO;
}