/**
 * RBAC example API
 * RBAC NestJS API with openapi integration for API client generation.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostDTO } from './postDTO';

export interface ProfileDTO { 
    /**
     * Profile ID
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * User Email
     */
    email: string;
    /**
     * User role
     */
    role: string;
    /**
     * User posts.
     */
    posts: Array<PostDTO>;
}