/**
 * RBAC example API
 * RBAC NestJS API with openapi integration for API client generation.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TokenDto { 
    /**
     * JWT access token
     */
    access_token: string;
}